_wandb:
    value:
        cli_version: 0.25.1
        e:
            uza8n3c4511jj0macaquvmpoen64ky3f:
                codePath: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/move2.ipynb
                codePathLocal: move2.ipynb
                email: kejian.zhao@tsings.cn
                executable: /root/anaconda3/envs/zkj-work/bin/python
                git:
                    commit: 308142aa50adf2e187711354f7524635d3414f1e
                    remote: https://github.com/mk-minchul/CVLface.git
                host: star
                os: Linux-5.15.0-170-generic-x86_64-with-glibc2.35
                program: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/move2.ipynb
                python: CPython 3.12.0
                root: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213
                startedAt: "2026-03-19T09:27:20.393310Z"
                writerId: uza8n3c4511jj0macaquvmpoen64ky3f
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.0
        t:
            "3":
                - 2
                - 5
                - 7
                - 13
                - 14
                - 62
            "4": 3.12.0
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
