data_root: '/data2/dataset_0213_rec'
eval_every_n_epochs: 1
per_epoch_evaluations: {
  "ijbc": {
    'path': 'facerec_val/IJBC_gt_aligned',
    'evaluation_type': 'ijbc_custom',
    'color_space': 'RGB',
    'batch_size': 512,
    'num_workers': 5
  },
  "work": {
    'path': 'test',
    'evaluation_type': 'custom_verification4',
    'color_space': 'RGB',
    'batch_size': 512,
    'num_workers': 5
  },
  "work_1201": {
    'path': 'test_1201',
    'evaluation_type': 'custom_verification4',
    'color_space': 'RGB',
    'batch_size': 512,
    'num_workers': 5
  },
   "IJBC_gt_aligned": {
    'path': 'facerec_val/IJBC_gt_aligned',
    'evaluation_type': 'ijbbc',
    'color_space': 'RGB',
    'batch_size': 512,
    'num_workers': 5
  },
  
}

