_wandb:
    value:
        cli_version: 0.25.1
        e:
            wpzalf5mtykjktu95gsochgysomdxbws:
                codePath: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0320/move2.ipynb
                codePathLocal: move2.ipynb
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "942725181440"
                        used: "731997114368"
                email: kejian.zhao@tsings.cn
                executable: /root/anaconda3/envs/zkj-work/bin/python
                git:
                    commit: 308142aa50adf2e187711354f7524635d3414f1e
                    remote: https://github.com/mk-minchul/CVLface.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-da714a54-b5d4-c753-0caf-4f58ddf15712
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-fcf4eceb-ddc5-a4d8-2f52-f759495400b1
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-732d1980-28c5-27e3-5b99-ca9aab2ce212
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-092e7127-3283-723a-2e20-40cb0cb2edf7
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-3eae1ea8-6a0b-151e-7cf2-5c673fa05cd6
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-bdbd878b-1341-4f1e-be85-130237a3e237
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-c6da140d-4ca2-9c8a-7b1f-a796beb80b53
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-1e2fca47-ee1b-b67d-ddea-3ec2209152f6
                host: star
                memory:
                    total: "540646285312"
                os: Linux-5.15.0-173-generic-x86_64-with-glibc2.35
                program: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0320/move2.ipynb
                python: CPython 3.12.0
                root: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0320
                startedAt: "2026-04-01T04:48:51.011870Z"
                writerId: wpzalf5mtykjktu95gsochgysomdxbws
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.0
        t:
            "3":
                - 2
                - 5
                - 7
                - 13
                - 14
                - 62
            "4": 3.12.0
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
