data_root: '/data2/dataset_0213_rec'
eval_every_n_epochs: 1
per_epoch_evaluations: {
  "work": {
    'path': 'val',
    'evaluation_type': 'custom_verification4',
    'color_space': 'RGB',
    'batch_size': 256,
    'num_workers': 5
  },
   "cplfw": {
    'path': 'facerec_val/cplfw',
    'evaluation_type': 'verification',
    'color_space': 'RGB',
    'batch_size': 256,
    'num_workers': 4
  },
  "calfw": {
    'path': 'facerec_val/calfw',
    'evaluation_type': 'verification',
    'color_space': 'RGB',
    'batch_size': 256,
    'num_workers': 4
  },
  "agedb_30": {
    'path': 'facerec_val/agedb_30',
    'evaluation_type': 'verification',
    'color_space': 'RGB',
    'batch_size': 256,
    'num_workers': 4
  },
  "tinyface": {
    'path': 'facerec_val/tinyface_aligned_pad_0.1',
    'evaluation_type': 'tinyface',
    'color_space': 'RGB',
    'batch_size': 256,
    'num_workers': 4
  },
}

