_wandb:
    value:
        cli_version: 0.25.1
        e:
            2ojkny4jjykj9h26gmgwzfavcotxkozg:
                codePath: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/move.ipynb
                codePathLocal: move.ipynb
                email: kejian.zhao@tsings.cn
                executable: /root/anaconda3/envs/zkj-work/bin/python
                git:
                    commit: 308142aa50adf2e187711354f7524635d3414f1e
                    remote: https://github.com/mk-minchul/CVLface.git
                host: star
                os: Linux-5.15.0-170-generic-x86_64-with-glibc2.35
                program: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/move.ipynb
                python: CPython 3.12.0
                root: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213
                startedAt: "2026-03-18T10:04:47.332132Z"
                writerId: 2ojkny4jjykj9h26gmgwzfavcotxkozg
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.0
        t:
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 62
            "4": 3.12.0
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
