_wandb:
    value:
        cli_version: 0.25.1
        e:
            r8gk5ddrw0fhg7hgbum6skt3ai52dbha:
                codePath: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/move.ipynb
                codePathLocal: move.ipynb
                email: kejian.zhao@tsings.cn
                executable: /root/anaconda3/envs/zkj-work/bin/python
                host: star
                os: Linux-5.15.0-170-generic-x86_64-with-glibc2.35
                program: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/move.ipynb
                python: CPython 3.12.0
                root: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213
                startedAt: "2026-03-19T07:53:01.642493Z"
                writerId: r8gk5ddrw0fhg7hgbum6skt3ai52dbha
        m:
            - "1": trainer/epoch
              "6":
                - 3
              "7": []
            - "1": summary/IJBC_TPR@FPR0.01
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.0
        t:
            "3":
                - 2
                - 5
                - 7
                - 13
                - 14
                - 62
            "4": 3.12.0
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
