_wandb:
    value:
        cli_version: 0.25.1
        e:
            uu1qcg78q9nvn3ni9tgpd47nkadg92ta:
                codePath: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/wandb.ipynb
                codePathLocal: wandb.ipynb
                cpu_count: 64
                cpu_count_logical: 128
                disk:
                    /:
                        total: "942725181440"
                        used: "650066280448"
                email: kejian.zhao@tsings.cn
                executable: /root/anaconda3/envs/zkj-work/bin/python
                git:
                    commit: 308142aa50adf2e187711354f7524635d3414f1e
                    remote: https://github.com/mk-minchul/CVLface.git
                host: star
                memory:
                    total: "540646264832"
                os: Linux-5.15.0-170-generic-x86_64-with-glibc2.35
                program: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213/wandb.ipynb
                python: CPython 3.12.0
                root: /root/zhaokj/CVLface/cvlface/research/recognition/code/work_0213
                startedAt: "2026-03-14T03:47:25.271002Z"
                writerId: uu1qcg78q9nvn3ni9tgpd47nkadg92ta
        m: []
        python_version: 3.12.0
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.0
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
